### PR TITLE
CVC Validation + Firefox compatability

### PR DESCRIPTION
**Pull request by 8bitDesigner**
- Resolve compatibility issues with Firefox
- Limit AmEx CVC validation to 4 digits
- Harden CVC validation

### CODE REVIEW

**Comment by oitozero** [comment]
+1

Please, merge this PR. We had issues using angular-payments in Firefox.
cc/ @8bitDesigner

**Comment by drewfreyling** [comment]
Agreed. This issue has been around way too long.

**Comment by mdurn** [comment]
+1

**Comment by tommymcdonald** [comment]
Need this for sure, +1 please merge

**Comment by drewfreyling** [comment]
If it doesn't get merged, the "should we fork it and contribute from there" convo might have to happen.

**Comment by tommymcdonald** [comment]
@drewfreyling we've already begun that process here if you'd like to contribute. https://github.com/HonestDollar/angular-payments

**Comment by drewfreyling** [comment]
We should get @8bitDesigner to submit his PR there. As an aside I can also get it into cdnjs too if the community would like.

**Comment by kiran-jose** [comment]
+1
This  issue needs to be resolved. Please merge this pull request. 
@laurihy Would like to know when a fix for this issue will be available in the package?

**Pull request closed without merging**
